spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bookdetails?useSSL=false
    username: root
    password : 631asachinmitralane

  #Jpa Settings
  jpa:
    hibernate:
      ddl-auto: create


